services:
  # Express API server
  - type: web
    name: task4-server
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false  
      - key: SESSION_SECRET
        sync: false 
      - key: EMAIL_USER
        sync: false 
      - key: EMAIL_PASS
        sync: false  
      - key: CLIENT_URL
        sync: false 
      - key: BASE_URL
        sync: false 


  - type: web
    name: task4-client
    runtime: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        sync: false  

databases:
  - name: task4-db
    databaseName: task4
    user: task4user
    plan: free
